//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4927
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLKS.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("QLKS.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static System.Drawing.Bitmap ButtonAdd {
            get {
                object obj = ResourceManager.GetObject("ButtonAdd", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ButtonAddFocus {
            get {
                object obj = ResourceManager.GetObject("ButtonAddFocus", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ButtonChecked {
            get {
                object obj = ResourceManager.GetObject("ButtonChecked", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ButtonCheckedFocus {
            get {
                object obj = ResourceManager.GetObject("ButtonCheckedFocus", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ButtonCustomer {
            get {
                object obj = ResourceManager.GetObject("ButtonCustomer", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ButtonCustomerFocus {
            get {
                object obj = ResourceManager.GetObject("ButtonCustomerFocus", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ButtonDatPhong {
            get {
                object obj = ResourceManager.GetObject("ButtonDatPhong", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ButtonDatPhongFocus {
            get {
                object obj = ResourceManager.GetObject("ButtonDatPhongFocus", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ButtonDelete {
            get {
                object obj = ResourceManager.GetObject("ButtonDelete", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ButtonDeleteFocus {
            get {
                object obj = ResourceManager.GetObject("ButtonDeleteFocus", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ButtonExit {
            get {
                object obj = ResourceManager.GetObject("ButtonExit", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ButtonExitFocus {
            get {
                object obj = ResourceManager.GetObject("ButtonExitFocus", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ButtonFix {
            get {
                object obj = ResourceManager.GetObject("ButtonFix", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ButtonFixFocus {
            get {
                object obj = ResourceManager.GetObject("ButtonFixFocus", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ButtonFocus_Lui {
            get {
                object obj = ResourceManager.GetObject("ButtonFocus_Lui", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ButtonFocus_Toi {
            get {
                object obj = ResourceManager.GetObject("ButtonFocus_Toi", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ButtonLui {
            get {
                object obj = ResourceManager.GetObject("ButtonLui", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ButtonMatrixTick {
            get {
                object obj = ResourceManager.GetObject("ButtonMatrixTick", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ButtonMatrixTickFocus {
            get {
                object obj = ResourceManager.GetObject("ButtonMatrixTickFocus", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ButtonMinimize {
            get {
                object obj = ResourceManager.GetObject("ButtonMinimize", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ButtonMinimizeFocus {
            get {
                object obj = ResourceManager.GetObject("ButtonMinimizeFocus", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ButtonMoneyReport {
            get {
                object obj = ResourceManager.GetObject("ButtonMoneyReport", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ButtonMoneyReportFocus {
            get {
                object obj = ResourceManager.GetObject("ButtonMoneyReportFocus", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ButtonNhanHet {
            get {
                object obj = ResourceManager.GetObject("ButtonNhanHet", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ButtonNhanHetFocus {
            get {
                object obj = ResourceManager.GetObject("ButtonNhanHetFocus", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ButtonNhanPhong {
            get {
                object obj = ResourceManager.GetObject("ButtonNhanPhong", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ButtonNhanPhongFocus {
            get {
                object obj = ResourceManager.GetObject("ButtonNhanPhongFocus", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ButtonQuayLai {
            get {
                object obj = ResourceManager.GetObject("ButtonQuayLai", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ButtonQuayLaiFocus {
            get {
                object obj = ResourceManager.GetObject("ButtonQuayLaiFocus", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ButtonRoom {
            get {
                object obj = ResourceManager.GetObject("ButtonRoom", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ButtonRoomFocus {
            get {
                object obj = ResourceManager.GetObject("ButtonRoomFocus", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ButtonSearch {
            get {
                object obj = ResourceManager.GetObject("ButtonSearch", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ButtonSearchFocus {
            get {
                object obj = ResourceManager.GetObject("ButtonSearchFocus", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ButtonThem {
            get {
                object obj = ResourceManager.GetObject("ButtonThem", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ButtonThemFocus {
            get {
                object obj = ResourceManager.GetObject("ButtonThemFocus", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ButtonTick {
            get {
                object obj = ResourceManager.GetObject("ButtonTick", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ButtonTickFocus {
            get {
                object obj = ResourceManager.GetObject("ButtonTickFocus", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ButtonToi {
            get {
                object obj = ResourceManager.GetObject("ButtonToi", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ButtonTraPhong {
            get {
                object obj = ResourceManager.GetObject("ButtonTraPhong", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ButtonTraPhongFocus {
            get {
                object obj = ResourceManager.GetObject("ButtonTraPhongFocus", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ButtonXacNhan {
            get {
                object obj = ResourceManager.GetObject("ButtonXacNhan", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ButtonXacNhanFocus {
            get {
                object obj = ResourceManager.GetObject("ButtonXacNhanFocus", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ButtonXoa {
            get {
                object obj = ResourceManager.GetObject("ButtonXoa", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ButtonXoaFocus {
            get {
                object obj = ResourceManager.GetObject("ButtonXoaFocus", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap MainMenu {
            get {
                object obj = ResourceManager.GetObject("MainMenu", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap MHBCDoanhThuThang {
            get {
                object obj = ResourceManager.GetObject("MHBCDoanhThuThang", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap MHDatPhong {
            get {
                object obj = ResourceManager.GetObject("MHDatPhong", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap MHSuaPhong {
            get {
                object obj = ResourceManager.GetObject("MHSuaPhong", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap MHThemPhong {
            get {
                object obj = ResourceManager.GetObject("MHThemPhong", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap MHTiepNhanDatPhong {
            get {
                object obj = ResourceManager.GetObject("MHTiepNhanDatPhong", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap MHTraCuuKhachHang {
            get {
                object obj = ResourceManager.GetObject("MHTraCuuKhachHang", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap MHTraCuuPhieuThue {
            get {
                object obj = ResourceManager.GetObject("MHTraCuuPhieuThue", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap MHTraCuuPhong {
            get {
                object obj = ResourceManager.GetObject("MHTraCuuPhong", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap MHXoaPhong {
            get {
                object obj = ResourceManager.GetObject("MHXoaPhong", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap NhanPhong {
            get {
                object obj = ResourceManager.GetObject("NhanPhong", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap reservation {
            get {
                object obj = ResourceManager.GetObject("reservation", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap reservation1 {
            get {
                object obj = ResourceManager.GetObject("reservation1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap TraPhong {
            get {
                object obj = ResourceManager.GetObject("TraPhong", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
