//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4927
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace G2_QLKS.WebService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PHONG", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class PHONG : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MaPhongField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TenPhongField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MaLoaiPhongField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string GhiChuField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TinhTrangField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string MaPhong {
            get {
                return this.MaPhongField;
            }
            set {
                if ((object.ReferenceEquals(this.MaPhongField, value) != true)) {
                    this.MaPhongField = value;
                    this.RaisePropertyChanged("MaPhong");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string TenPhong {
            get {
                return this.TenPhongField;
            }
            set {
                if ((object.ReferenceEquals(this.TenPhongField, value) != true)) {
                    this.TenPhongField = value;
                    this.RaisePropertyChanged("TenPhong");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string MaLoaiPhong {
            get {
                return this.MaLoaiPhongField;
            }
            set {
                if ((object.ReferenceEquals(this.MaLoaiPhongField, value) != true)) {
                    this.MaLoaiPhongField = value;
                    this.RaisePropertyChanged("MaLoaiPhong");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string GhiChu {
            get {
                return this.GhiChuField;
            }
            set {
                if ((object.ReferenceEquals(this.GhiChuField, value) != true)) {
                    this.GhiChuField = value;
                    this.RaisePropertyChanged("GhiChu");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string TinhTrang {
            get {
                return this.TinhTrangField;
            }
            set {
                if ((object.ReferenceEquals(this.TinhTrangField, value) != true)) {
                    this.TinhTrangField = value;
                    this.RaisePropertyChanged("TinhTrang");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="LOAIPHONG", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class LOAIPHONG : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MaLoaiPhongField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TenLoaiPhongField;
        
        private int DonGiaField;
        
        private int SLKhachToiDaField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string MaLoaiPhong {
            get {
                return this.MaLoaiPhongField;
            }
            set {
                if ((object.ReferenceEquals(this.MaLoaiPhongField, value) != true)) {
                    this.MaLoaiPhongField = value;
                    this.RaisePropertyChanged("MaLoaiPhong");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string TenLoaiPhong {
            get {
                return this.TenLoaiPhongField;
            }
            set {
                if ((object.ReferenceEquals(this.TenLoaiPhongField, value) != true)) {
                    this.TenLoaiPhongField = value;
                    this.RaisePropertyChanged("TenLoaiPhong");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public int DonGia {
            get {
                return this.DonGiaField;
            }
            set {
                if ((this.DonGiaField.Equals(value) != true)) {
                    this.DonGiaField = value;
                    this.RaisePropertyChanged("DonGia");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public int SLKhachToiDa {
            get {
                return this.SLKhachToiDaField;
            }
            set {
                if ((this.SLKhachToiDaField.Equals(value) != true)) {
                    this.SLKhachToiDaField = value;
                    this.RaisePropertyChanged("SLKhachToiDa");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PHIEUTHUE", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class PHIEUTHUE : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MaPhieuThueField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MaPhongField;
        
        private System.DateTime NgayThueField;
        
        private int SoNgayThueField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TenKhachHangDaiDienField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string MaPhieuThue {
            get {
                return this.MaPhieuThueField;
            }
            set {
                if ((object.ReferenceEquals(this.MaPhieuThueField, value) != true)) {
                    this.MaPhieuThueField = value;
                    this.RaisePropertyChanged("MaPhieuThue");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string MaPhong {
            get {
                return this.MaPhongField;
            }
            set {
                if ((object.ReferenceEquals(this.MaPhongField, value) != true)) {
                    this.MaPhongField = value;
                    this.RaisePropertyChanged("MaPhong");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.DateTime NgayThue {
            get {
                return this.NgayThueField;
            }
            set {
                if ((this.NgayThueField.Equals(value) != true)) {
                    this.NgayThueField = value;
                    this.RaisePropertyChanged("NgayThue");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int SoNgayThue {
            get {
                return this.SoNgayThueField;
            }
            set {
                if ((this.SoNgayThueField.Equals(value) != true)) {
                    this.SoNgayThueField = value;
                    this.RaisePropertyChanged("SoNgayThue");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string TenKhachHangDaiDien {
            get {
                return this.TenKhachHangDaiDienField;
            }
            set {
                if ((object.ReferenceEquals(this.TenKhachHangDaiDienField, value) != true)) {
                    this.TenKhachHangDaiDienField = value;
                    this.RaisePropertyChanged("TenKhachHangDaiDien");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="KHACHHANG", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class KHACHHANG : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MaKHField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string HoTenField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MaLoaiKHField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DiaChiField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SoGiayToField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string MaKH {
            get {
                return this.MaKHField;
            }
            set {
                if ((object.ReferenceEquals(this.MaKHField, value) != true)) {
                    this.MaKHField = value;
                    this.RaisePropertyChanged("MaKH");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string HoTen {
            get {
                return this.HoTenField;
            }
            set {
                if ((object.ReferenceEquals(this.HoTenField, value) != true)) {
                    this.HoTenField = value;
                    this.RaisePropertyChanged("HoTen");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string MaLoaiKH {
            get {
                return this.MaLoaiKHField;
            }
            set {
                if ((object.ReferenceEquals(this.MaLoaiKHField, value) != true)) {
                    this.MaLoaiKHField = value;
                    this.RaisePropertyChanged("MaLoaiKH");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string DiaChi {
            get {
                return this.DiaChiField;
            }
            set {
                if ((object.ReferenceEquals(this.DiaChiField, value) != true)) {
                    this.DiaChiField = value;
                    this.RaisePropertyChanged("DiaChi");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string SoGiayTo {
            get {
                return this.SoGiayToField;
            }
            set {
                if ((object.ReferenceEquals(this.SoGiayToField, value) != true)) {
                    this.SoGiayToField = value;
                    this.RaisePropertyChanged("SoGiayTo");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="HOADON", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class HOADON : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MaHoaDonField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TenKhachHangThanhToanField;
        
        private System.DateTime NgayThanhToanField;
        
        private int ThanhtienField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MaPhieuThueField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string MaHoaDon {
            get {
                return this.MaHoaDonField;
            }
            set {
                if ((object.ReferenceEquals(this.MaHoaDonField, value) != true)) {
                    this.MaHoaDonField = value;
                    this.RaisePropertyChanged("MaHoaDon");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string TenKhachHangThanhToan {
            get {
                return this.TenKhachHangThanhToanField;
            }
            set {
                if ((object.ReferenceEquals(this.TenKhachHangThanhToanField, value) != true)) {
                    this.TenKhachHangThanhToanField = value;
                    this.RaisePropertyChanged("TenKhachHangThanhToan");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public System.DateTime NgayThanhToan {
            get {
                return this.NgayThanhToanField;
            }
            set {
                if ((this.NgayThanhToanField.Equals(value) != true)) {
                    this.NgayThanhToanField = value;
                    this.RaisePropertyChanged("NgayThanhToan");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public int Thanhtien {
            get {
                return this.ThanhtienField;
            }
            set {
                if ((this.ThanhtienField.Equals(value) != true)) {
                    this.ThanhtienField = value;
                    this.RaisePropertyChanged("Thanhtien");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string MaPhieuThue {
            get {
                return this.MaPhieuThueField;
            }
            set {
                if ((object.ReferenceEquals(this.MaPhieuThueField, value) != true)) {
                    this.MaPhieuThueField = value;
                    this.RaisePropertyChanged("MaPhieuThue");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WebService.Service1Soap")]
    public interface Service1Soap {
        
        // CODEGEN: Generating message contract since element name pbLayDSPhongResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/pbLayDSPhong", ReplyAction="*")]
        G2_QLKS.WebService.pbLayDSPhongResponse pbLayDSPhong(G2_QLKS.WebService.pbLayDSPhongRequest request);
        
        // CODEGEN: Generating message contract since element name loaiPhong from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/pbLayDSPhongTheoLoaiPhong", ReplyAction="*")]
        G2_QLKS.WebService.pbLayDSPhongTheoLoaiPhongResponse pbLayDSPhongTheoLoaiPhong(G2_QLKS.WebService.pbLayDSPhongTheoLoaiPhongRequest request);
        
        // CODEGEN: Generating message contract since element name pbLayDSLoaiPhongResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/pbLayDSLoaiPhong", ReplyAction="*")]
        G2_QLKS.WebService.pbLayDSLoaiPhongResponse pbLayDSLoaiPhong(G2_QLKS.WebService.pbLayDSLoaiPhongRequest request);
        
        // CODEGEN: Generating message contract since element name phong from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/pbThemPhong", ReplyAction="*")]
        G2_QLKS.WebService.pbThemPhongResponse pbThemPhong(G2_QLKS.WebService.pbThemPhongRequest request);
        
        // CODEGEN: Generating message contract since element name MP from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/pbXoaPhong", ReplyAction="*")]
        G2_QLKS.WebService.pbXoaPhongResponse pbXoaPhong(G2_QLKS.WebService.pbXoaPhongRequest request);
        
        // CODEGEN: Generating message contract since element name phong from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ptbLayDSPhieuThueTheoPhong", ReplyAction="*")]
        G2_QLKS.WebService.ptbLayDSPhieuThueTheoPhongResponse ptbLayDSPhieuThueTheoPhong(G2_QLKS.WebService.ptbLayDSPhieuThueTheoPhongRequest request);
        
        // CODEGEN: Generating message contract since element name khbLayDSKhachResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/khbLayDSKhach", ReplyAction="*")]
        G2_QLKS.WebService.khbLayDSKhachResponse khbLayDSKhach(G2_QLKS.WebService.khbLayDSKhachRequest request);
        
        // CODEGEN: Generating message contract since element name hdblayDSHoaDonResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/hdblayDSHoaDon", ReplyAction="*")]
        G2_QLKS.WebService.hdblayDSHoaDonResponse hdblayDSHoaDon(G2_QLKS.WebService.hdblayDSHoaDonRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class pbLayDSPhongRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="pbLayDSPhong", Namespace="http://tempuri.org/", Order=0)]
        public G2_QLKS.WebService.pbLayDSPhongRequestBody Body;
        
        public pbLayDSPhongRequest() {
        }
        
        public pbLayDSPhongRequest(G2_QLKS.WebService.pbLayDSPhongRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class pbLayDSPhongRequestBody {
        
        public pbLayDSPhongRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class pbLayDSPhongResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="pbLayDSPhongResponse", Namespace="http://tempuri.org/", Order=0)]
        public G2_QLKS.WebService.pbLayDSPhongResponseBody Body;
        
        public pbLayDSPhongResponse() {
        }
        
        public pbLayDSPhongResponse(G2_QLKS.WebService.pbLayDSPhongResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class pbLayDSPhongResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public G2_QLKS.WebService.PHONG[] pbLayDSPhongResult;
        
        public pbLayDSPhongResponseBody() {
        }
        
        public pbLayDSPhongResponseBody(G2_QLKS.WebService.PHONG[] pbLayDSPhongResult) {
            this.pbLayDSPhongResult = pbLayDSPhongResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class pbLayDSPhongTheoLoaiPhongRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="pbLayDSPhongTheoLoaiPhong", Namespace="http://tempuri.org/", Order=0)]
        public G2_QLKS.WebService.pbLayDSPhongTheoLoaiPhongRequestBody Body;
        
        public pbLayDSPhongTheoLoaiPhongRequest() {
        }
        
        public pbLayDSPhongTheoLoaiPhongRequest(G2_QLKS.WebService.pbLayDSPhongTheoLoaiPhongRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class pbLayDSPhongTheoLoaiPhongRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public G2_QLKS.WebService.LOAIPHONG loaiPhong;
        
        public pbLayDSPhongTheoLoaiPhongRequestBody() {
        }
        
        public pbLayDSPhongTheoLoaiPhongRequestBody(G2_QLKS.WebService.LOAIPHONG loaiPhong) {
            this.loaiPhong = loaiPhong;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class pbLayDSPhongTheoLoaiPhongResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="pbLayDSPhongTheoLoaiPhongResponse", Namespace="http://tempuri.org/", Order=0)]
        public G2_QLKS.WebService.pbLayDSPhongTheoLoaiPhongResponseBody Body;
        
        public pbLayDSPhongTheoLoaiPhongResponse() {
        }
        
        public pbLayDSPhongTheoLoaiPhongResponse(G2_QLKS.WebService.pbLayDSPhongTheoLoaiPhongResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class pbLayDSPhongTheoLoaiPhongResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public G2_QLKS.WebService.PHONG[] pbLayDSPhongTheoLoaiPhongResult;
        
        public pbLayDSPhongTheoLoaiPhongResponseBody() {
        }
        
        public pbLayDSPhongTheoLoaiPhongResponseBody(G2_QLKS.WebService.PHONG[] pbLayDSPhongTheoLoaiPhongResult) {
            this.pbLayDSPhongTheoLoaiPhongResult = pbLayDSPhongTheoLoaiPhongResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class pbLayDSLoaiPhongRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="pbLayDSLoaiPhong", Namespace="http://tempuri.org/", Order=0)]
        public G2_QLKS.WebService.pbLayDSLoaiPhongRequestBody Body;
        
        public pbLayDSLoaiPhongRequest() {
        }
        
        public pbLayDSLoaiPhongRequest(G2_QLKS.WebService.pbLayDSLoaiPhongRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class pbLayDSLoaiPhongRequestBody {
        
        public pbLayDSLoaiPhongRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class pbLayDSLoaiPhongResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="pbLayDSLoaiPhongResponse", Namespace="http://tempuri.org/", Order=0)]
        public G2_QLKS.WebService.pbLayDSLoaiPhongResponseBody Body;
        
        public pbLayDSLoaiPhongResponse() {
        }
        
        public pbLayDSLoaiPhongResponse(G2_QLKS.WebService.pbLayDSLoaiPhongResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class pbLayDSLoaiPhongResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public G2_QLKS.WebService.LOAIPHONG[] pbLayDSLoaiPhongResult;
        
        public pbLayDSLoaiPhongResponseBody() {
        }
        
        public pbLayDSLoaiPhongResponseBody(G2_QLKS.WebService.LOAIPHONG[] pbLayDSLoaiPhongResult) {
            this.pbLayDSLoaiPhongResult = pbLayDSLoaiPhongResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class pbThemPhongRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="pbThemPhong", Namespace="http://tempuri.org/", Order=0)]
        public G2_QLKS.WebService.pbThemPhongRequestBody Body;
        
        public pbThemPhongRequest() {
        }
        
        public pbThemPhongRequest(G2_QLKS.WebService.pbThemPhongRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class pbThemPhongRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public G2_QLKS.WebService.PHONG phong;
        
        public pbThemPhongRequestBody() {
        }
        
        public pbThemPhongRequestBody(G2_QLKS.WebService.PHONG phong) {
            this.phong = phong;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class pbThemPhongResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="pbThemPhongResponse", Namespace="http://tempuri.org/", Order=0)]
        public G2_QLKS.WebService.pbThemPhongResponseBody Body;
        
        public pbThemPhongResponse() {
        }
        
        public pbThemPhongResponse(G2_QLKS.WebService.pbThemPhongResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class pbThemPhongResponseBody {
        
        public pbThemPhongResponseBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class pbXoaPhongRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="pbXoaPhong", Namespace="http://tempuri.org/", Order=0)]
        public G2_QLKS.WebService.pbXoaPhongRequestBody Body;
        
        public pbXoaPhongRequest() {
        }
        
        public pbXoaPhongRequest(G2_QLKS.WebService.pbXoaPhongRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class pbXoaPhongRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string MP;
        
        public pbXoaPhongRequestBody() {
        }
        
        public pbXoaPhongRequestBody(string MP) {
            this.MP = MP;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class pbXoaPhongResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="pbXoaPhongResponse", Namespace="http://tempuri.org/", Order=0)]
        public G2_QLKS.WebService.pbXoaPhongResponseBody Body;
        
        public pbXoaPhongResponse() {
        }
        
        public pbXoaPhongResponse(G2_QLKS.WebService.pbXoaPhongResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class pbXoaPhongResponseBody {
        
        public pbXoaPhongResponseBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ptbLayDSPhieuThueTheoPhongRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ptbLayDSPhieuThueTheoPhong", Namespace="http://tempuri.org/", Order=0)]
        public G2_QLKS.WebService.ptbLayDSPhieuThueTheoPhongRequestBody Body;
        
        public ptbLayDSPhieuThueTheoPhongRequest() {
        }
        
        public ptbLayDSPhieuThueTheoPhongRequest(G2_QLKS.WebService.ptbLayDSPhieuThueTheoPhongRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ptbLayDSPhieuThueTheoPhongRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public G2_QLKS.WebService.PHONG phong;
        
        public ptbLayDSPhieuThueTheoPhongRequestBody() {
        }
        
        public ptbLayDSPhieuThueTheoPhongRequestBody(G2_QLKS.WebService.PHONG phong) {
            this.phong = phong;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ptbLayDSPhieuThueTheoPhongResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ptbLayDSPhieuThueTheoPhongResponse", Namespace="http://tempuri.org/", Order=0)]
        public G2_QLKS.WebService.ptbLayDSPhieuThueTheoPhongResponseBody Body;
        
        public ptbLayDSPhieuThueTheoPhongResponse() {
        }
        
        public ptbLayDSPhieuThueTheoPhongResponse(G2_QLKS.WebService.ptbLayDSPhieuThueTheoPhongResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ptbLayDSPhieuThueTheoPhongResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public G2_QLKS.WebService.PHIEUTHUE[] ptbLayDSPhieuThueTheoPhongResult;
        
        public ptbLayDSPhieuThueTheoPhongResponseBody() {
        }
        
        public ptbLayDSPhieuThueTheoPhongResponseBody(G2_QLKS.WebService.PHIEUTHUE[] ptbLayDSPhieuThueTheoPhongResult) {
            this.ptbLayDSPhieuThueTheoPhongResult = ptbLayDSPhieuThueTheoPhongResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class khbLayDSKhachRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="khbLayDSKhach", Namespace="http://tempuri.org/", Order=0)]
        public G2_QLKS.WebService.khbLayDSKhachRequestBody Body;
        
        public khbLayDSKhachRequest() {
        }
        
        public khbLayDSKhachRequest(G2_QLKS.WebService.khbLayDSKhachRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class khbLayDSKhachRequestBody {
        
        public khbLayDSKhachRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class khbLayDSKhachResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="khbLayDSKhachResponse", Namespace="http://tempuri.org/", Order=0)]
        public G2_QLKS.WebService.khbLayDSKhachResponseBody Body;
        
        public khbLayDSKhachResponse() {
        }
        
        public khbLayDSKhachResponse(G2_QLKS.WebService.khbLayDSKhachResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class khbLayDSKhachResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public G2_QLKS.WebService.KHACHHANG[] khbLayDSKhachResult;
        
        public khbLayDSKhachResponseBody() {
        }
        
        public khbLayDSKhachResponseBody(G2_QLKS.WebService.KHACHHANG[] khbLayDSKhachResult) {
            this.khbLayDSKhachResult = khbLayDSKhachResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class hdblayDSHoaDonRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="hdblayDSHoaDon", Namespace="http://tempuri.org/", Order=0)]
        public G2_QLKS.WebService.hdblayDSHoaDonRequestBody Body;
        
        public hdblayDSHoaDonRequest() {
        }
        
        public hdblayDSHoaDonRequest(G2_QLKS.WebService.hdblayDSHoaDonRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class hdblayDSHoaDonRequestBody {
        
        public hdblayDSHoaDonRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class hdblayDSHoaDonResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="hdblayDSHoaDonResponse", Namespace="http://tempuri.org/", Order=0)]
        public G2_QLKS.WebService.hdblayDSHoaDonResponseBody Body;
        
        public hdblayDSHoaDonResponse() {
        }
        
        public hdblayDSHoaDonResponse(G2_QLKS.WebService.hdblayDSHoaDonResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class hdblayDSHoaDonResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public G2_QLKS.WebService.HOADON[] hdblayDSHoaDonResult;
        
        public hdblayDSHoaDonResponseBody() {
        }
        
        public hdblayDSHoaDonResponseBody(G2_QLKS.WebService.HOADON[] hdblayDSHoaDonResult) {
            this.hdblayDSHoaDonResult = hdblayDSHoaDonResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public interface Service1SoapChannel : G2_QLKS.WebService.Service1Soap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public partial class Service1SoapClient : System.ServiceModel.ClientBase<G2_QLKS.WebService.Service1Soap>, G2_QLKS.WebService.Service1Soap {
        
        public Service1SoapClient() {
        }
        
        public Service1SoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1SoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1SoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1SoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        G2_QLKS.WebService.pbLayDSPhongResponse G2_QLKS.WebService.Service1Soap.pbLayDSPhong(G2_QLKS.WebService.pbLayDSPhongRequest request) {
            return base.Channel.pbLayDSPhong(request);
        }
        
        public G2_QLKS.WebService.PHONG[] pbLayDSPhong() {
            G2_QLKS.WebService.pbLayDSPhongRequest inValue = new G2_QLKS.WebService.pbLayDSPhongRequest();
            inValue.Body = new G2_QLKS.WebService.pbLayDSPhongRequestBody();
            G2_QLKS.WebService.pbLayDSPhongResponse retVal = ((G2_QLKS.WebService.Service1Soap)(this)).pbLayDSPhong(inValue);
            return retVal.Body.pbLayDSPhongResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        G2_QLKS.WebService.pbLayDSPhongTheoLoaiPhongResponse G2_QLKS.WebService.Service1Soap.pbLayDSPhongTheoLoaiPhong(G2_QLKS.WebService.pbLayDSPhongTheoLoaiPhongRequest request) {
            return base.Channel.pbLayDSPhongTheoLoaiPhong(request);
        }
        
        public G2_QLKS.WebService.PHONG[] pbLayDSPhongTheoLoaiPhong(G2_QLKS.WebService.LOAIPHONG loaiPhong) {
            G2_QLKS.WebService.pbLayDSPhongTheoLoaiPhongRequest inValue = new G2_QLKS.WebService.pbLayDSPhongTheoLoaiPhongRequest();
            inValue.Body = new G2_QLKS.WebService.pbLayDSPhongTheoLoaiPhongRequestBody();
            inValue.Body.loaiPhong = loaiPhong;
            G2_QLKS.WebService.pbLayDSPhongTheoLoaiPhongResponse retVal = ((G2_QLKS.WebService.Service1Soap)(this)).pbLayDSPhongTheoLoaiPhong(inValue);
            return retVal.Body.pbLayDSPhongTheoLoaiPhongResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        G2_QLKS.WebService.pbLayDSLoaiPhongResponse G2_QLKS.WebService.Service1Soap.pbLayDSLoaiPhong(G2_QLKS.WebService.pbLayDSLoaiPhongRequest request) {
            return base.Channel.pbLayDSLoaiPhong(request);
        }
        
        public G2_QLKS.WebService.LOAIPHONG[] pbLayDSLoaiPhong() {
            G2_QLKS.WebService.pbLayDSLoaiPhongRequest inValue = new G2_QLKS.WebService.pbLayDSLoaiPhongRequest();
            inValue.Body = new G2_QLKS.WebService.pbLayDSLoaiPhongRequestBody();
            G2_QLKS.WebService.pbLayDSLoaiPhongResponse retVal = ((G2_QLKS.WebService.Service1Soap)(this)).pbLayDSLoaiPhong(inValue);
            return retVal.Body.pbLayDSLoaiPhongResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        G2_QLKS.WebService.pbThemPhongResponse G2_QLKS.WebService.Service1Soap.pbThemPhong(G2_QLKS.WebService.pbThemPhongRequest request) {
            return base.Channel.pbThemPhong(request);
        }
        
        public void pbThemPhong(G2_QLKS.WebService.PHONG phong) {
            G2_QLKS.WebService.pbThemPhongRequest inValue = new G2_QLKS.WebService.pbThemPhongRequest();
            inValue.Body = new G2_QLKS.WebService.pbThemPhongRequestBody();
            inValue.Body.phong = phong;
            G2_QLKS.WebService.pbThemPhongResponse retVal = ((G2_QLKS.WebService.Service1Soap)(this)).pbThemPhong(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        G2_QLKS.WebService.pbXoaPhongResponse G2_QLKS.WebService.Service1Soap.pbXoaPhong(G2_QLKS.WebService.pbXoaPhongRequest request) {
            return base.Channel.pbXoaPhong(request);
        }
        
        public void pbXoaPhong(string MP) {
            G2_QLKS.WebService.pbXoaPhongRequest inValue = new G2_QLKS.WebService.pbXoaPhongRequest();
            inValue.Body = new G2_QLKS.WebService.pbXoaPhongRequestBody();
            inValue.Body.MP = MP;
            G2_QLKS.WebService.pbXoaPhongResponse retVal = ((G2_QLKS.WebService.Service1Soap)(this)).pbXoaPhong(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        G2_QLKS.WebService.ptbLayDSPhieuThueTheoPhongResponse G2_QLKS.WebService.Service1Soap.ptbLayDSPhieuThueTheoPhong(G2_QLKS.WebService.ptbLayDSPhieuThueTheoPhongRequest request) {
            return base.Channel.ptbLayDSPhieuThueTheoPhong(request);
        }
        
        public G2_QLKS.WebService.PHIEUTHUE[] ptbLayDSPhieuThueTheoPhong(G2_QLKS.WebService.PHONG phong) {
            G2_QLKS.WebService.ptbLayDSPhieuThueTheoPhongRequest inValue = new G2_QLKS.WebService.ptbLayDSPhieuThueTheoPhongRequest();
            inValue.Body = new G2_QLKS.WebService.ptbLayDSPhieuThueTheoPhongRequestBody();
            inValue.Body.phong = phong;
            G2_QLKS.WebService.ptbLayDSPhieuThueTheoPhongResponse retVal = ((G2_QLKS.WebService.Service1Soap)(this)).ptbLayDSPhieuThueTheoPhong(inValue);
            return retVal.Body.ptbLayDSPhieuThueTheoPhongResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        G2_QLKS.WebService.khbLayDSKhachResponse G2_QLKS.WebService.Service1Soap.khbLayDSKhach(G2_QLKS.WebService.khbLayDSKhachRequest request) {
            return base.Channel.khbLayDSKhach(request);
        }
        
        public G2_QLKS.WebService.KHACHHANG[] khbLayDSKhach() {
            G2_QLKS.WebService.khbLayDSKhachRequest inValue = new G2_QLKS.WebService.khbLayDSKhachRequest();
            inValue.Body = new G2_QLKS.WebService.khbLayDSKhachRequestBody();
            G2_QLKS.WebService.khbLayDSKhachResponse retVal = ((G2_QLKS.WebService.Service1Soap)(this)).khbLayDSKhach(inValue);
            return retVal.Body.khbLayDSKhachResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        G2_QLKS.WebService.hdblayDSHoaDonResponse G2_QLKS.WebService.Service1Soap.hdblayDSHoaDon(G2_QLKS.WebService.hdblayDSHoaDonRequest request) {
            return base.Channel.hdblayDSHoaDon(request);
        }
        
        public G2_QLKS.WebService.HOADON[] hdblayDSHoaDon() {
            G2_QLKS.WebService.hdblayDSHoaDonRequest inValue = new G2_QLKS.WebService.hdblayDSHoaDonRequest();
            inValue.Body = new G2_QLKS.WebService.hdblayDSHoaDonRequestBody();
            G2_QLKS.WebService.hdblayDSHoaDonResponse retVal = ((G2_QLKS.WebService.Service1Soap)(this)).hdblayDSHoaDon(inValue);
            return retVal.Body.hdblayDSHoaDonResult;
        }
    }
}
